name: "Stage Deploy"
inputs:
  token:
    description: "Github personal access token"
    default: ${{ github.token}}
  packages:
    description: "Packages info array"
    required: true
  docherhub-username:
    description: "DockerHub username"
    required: true
  docherhub-password:
    description: "DockerHub password"
    required: true
  dockerhub-namespace:
    description: "Dockerhub namespace"
    type: string
    required: true
  stage-directory:
    description: "Stage directory"
    type: string
  stage-file-prefix:
    description: "Stage file prefix"
    type: string
  stage-file-suffix:
    description: "Stage file prefix"
    type: string
runs:
  using: "node20"
  main: "dist/index.js"
