name: "Stage Deploy"
inputs:
  token:
    description: "Github personal access token"
    default: ${{ github.token}}
  packages:
    description: "Packages info array"
    required: true
  docherhub-username:
    description: "DockerHub username"
    required: true
  docherhub-password:
    description: "DockerHub password"
    required: true
  dockerhub-namespace:
    description: "Dockerhub namespace"
    type: string
    required: true
  stage-files:
    description: "<cr> delimited pairing of <Package name=Stage file name>"
    type: string
    required: true
  image-files:
    description: "<cr> delimited pairing of <Package name=Image file name>"
    type: string
    required: true
runs:
  using: "node22"
  main: "dist/index.js"
