name: "Publish Npm Packages"
inputs:
  token:
    description: "Github personal access token"
    default: ${{ github.token || env.GITHUB_TOKEN}}
  npm-token:
    description: "Access token for npm.pkg.github.com repository"
    default: ${{ env.GITHUB_TOKEN}}
  packages:
    description: "Packages info array"
    required: true
  workspace:
    description: "The default working directory on the runner for steps, and the default location of your repository when using the checkout action"
    default: ${{ github.workspace }}

runs:
  using: "node20"
  main: "dist/index.js"
