name: "Publish Npm Packages"
inputs:
  npm-token:
    description: "Access token for registry.npmjs.org repository"
  packages:
    description: "Packages info array"
    required: true
  workspace:
    description: "The default working directory on the runner for steps, and the default location of your repository when using the checkout action"
    default: ${{ github.workspace }}

runs:
  using: "node20"
  main: "dist/index.js"
