name: "Build Docker Images"
inputs:
  token:
    description: "Github personal access token"
    default: ${{ github.token}}
  packages:
    description: "Packages info array"
    required: true
  workspace:
    description: "The default working directory on the runner for steps, and the default location of your repository when using the checkout action"
    default: ${{ github.workspace }}
  platforms:
    description: "Comma seperated target platforms for Docker images. Default linux/amd64"
    default: 'linux/amd64'
    required: true
  docherhub-username:
    description: "DockerHub username"
    required: true
  docherhub-password:
    description: "DockerHub password"
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
