name: "Build Docker Images"
inputs:
  token:
    description: "Github personal access token"
    default: ${{ github.token}}
  packages:
    description: "Packages info array"
    required: true
  workspace:
    description: "The default working directory on the runner for steps, and the default location of your repository when using the checkout action"
    default: ${{ github.workspace }}
  platforms:
    description: "Comma seperated target platforms for Docker images. Default linux/amd64"
    default: 'linux/amd64'
    required: true
  docherhub-username:
    description: "DockerHub username"
    required: true
  docherhub-password:
    description: "DockerHub password"
    required: true
  dockerhub-namespace:
    description: "Dockerhub namespace"
    type: string
    required: true
  image-files:
    description: "<cr> delimited pairing of <Package name=Image file name>"
    type: string
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
