name: "Node Release"
inputs:
  token:
    description: "Github personal access token"
    required: true
  packages:
    description: "Packages info array"
    required: true
  dockerhub-username:
    description: "DockerHub username"
  dockerhub-password:
    description: "DockerHub password"
  docker-platforms:
    description: "Comma seperated target platforms for Docker images. Default linux/amd64,linux/arm64"

runs:
  using: "node20"
  main: "dist/index.js"
