name: "Publish Npm Packages"
inputs:
  token:
    description: "Github personal access token"
  packages:
    required: true
    description: "Packages info array"

runs:
  using: "node20"
  main: "dist/index.js"
