name: "GitHub Release"
on:
  workflow_call:
    inputs:
      tag:
        type: string
        description: "GitHub Release Tag"
        required: true
    secrets:
      PERSONAL_ACCESS_TOKEN:
        description: "Github personal access token"
        required: true
      DOCKERHUB_USERNAME:
        description: "DockerHub user name"
        required: false
      DOCKERHUB_PASS:
        description: "DockerHub password"
        required: false

jobs:
  # ***********************************
  # Job: Create GitHub release
  # ***********************************
  github_release:
    name: 'Create Github Release'
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: 'artifacts'
          path: './__artifacts__'

      - name: "Create ZIP files"
        uses: panates/github-actions/.github/actions/github-release-artifacts@dev

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ inputs.tag }}
          bodyFile: "__artifacts__/COMMIT_CHANGELOG.md"
          artifacts: "__release__/**/*"
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          draft: false
          prerelease: false
          replacesArtifacts: true
