name: Quality Check
on:
  workflow_call:
    inputs:
      qc_script:
        type: string
        description: "QC script to be executed"
        default: 'npm run qc'
      node-version:
        description: "NodeJS version"
        type: string
        default: "22.12"
    secrets:
      PERSONAL_ACCESS_TOKEN:
        description: "Github personal access token"
        required: true

jobs:

  # ***********************************
  # Job: Quality Check
  # ***********************************
  qc:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: panates/gh-setup-node@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          install-deps: "false"
          cache: "true"
          cache-key: "dev"
          node-version: ${{ inputs.node-version }}

      - name: Install dev dependencies
        run: |
          npm install --only=dev --no-save

      - name: Run QC Tests
        run: ${{ inputs.qc_script }}
