name: "Build"
on:
  workflow_call:
    inputs:
      build_script:
        type: string
        description: "Build script to be executed"
        default: 'npm run build'
    secrets:
      PERSONAL_ACCESS_TOKEN:
        description: "Github personal access token"
        required: true

jobs:
  # ***********************************
  # Job: Build Packages
  # ***********************************
  build:
    name: "Build Packages"
    runs-on: ubuntu-latest
    steps:
      - name: "Setup Environment"
        uses: panates/gh-setup-node@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: "Scan Environment"
        id: environment
        uses: panates/gh-repository-info@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: "Build Changelog"
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fromTag: ${{ steps.environment.outputs.prevSha }}
          toTag: ${{ steps.environment.outputs.lastSha }}
          mode: COMMIT
          outputFile: "COMMIT_CHANGELOG.md"
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n## Contributors:\n- #{{CONTRIBUTORS}}",
              "pr_template": "◉ #{{TITLE}}   (##{{NUMBER}})   by #{{AUTHOR_NAME}}  @#{{AUTHOR}}",
              "commit_template": "◉ #{{TITLE}}   by #{{AUTHOR_NAME}}  @#{{AUTHOR}}",
              "empty_template": "◉ no changes",
              "categories": [
                {
                  "title": "## 🚀 Features",
                  "labels": [
                    "feat",
                    "feature"
                  ]
                },
                {
                  "title": "## 🪲 Fixes",
                  "labels": [
                    "fix",
                    "bug"
                  ]
                },
                {
                  "title": "## 🛠️ Updates",
                  "labels": [
                    "refactor",
                    "update",
                    "perf",
                    "style"
                  ]
                },
                {
                  "title": "## 🧪 Tests",
                  "key": "tests",
                  "labels": [
                    "test"
                  ]
                },
                {
                  "title": "## 📖 Documentation",
                  "labels": [
                    "doc"
                  ]
                },
                {
                  "title": "## 💬 Other",
                  "labels": [
                    "build",
                    "ci"
                  ]
                }
              ],
              "ignore_labels": [
                "ignore",
                "chore",
                "dev",
                "style"
              ],
              "sort": {
                "order": "ASC",
                "on_property": "mergedAt"
              },
              "label_extractor": [
                {
                  "pattern": "^(feat|feature|fix|bug|refactor|update|perf|test|docs|build|ci|revert|chore|ignore|dev|style){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "target": "$1"
                }
              ]
            }

      - name: "Print changelog"
        run: |
          cat COMMIT_CHANGELOG.md

      #      - name: "Build"
      #        shell: bash
      #        run: |
      #          ${{ inputs.build_script }}
      #

      - name: Parse Directories
        uses: panates/github-actions/.github/actions/node-build@dev
        with:
          packages: ${{ steps.environment.outputs.packages }}
