name: "Build"
on:
  workflow_call:
    inputs:
      build_script:
        type: string
        description: "Build script to be executed"
        default: 'npm run build'
    outputs:
      lastVersion:
        type: string
        value: ${{ jobs.build.outputs.lastVersion }}
    secrets:
      PERSONAL_ACCESS_TOKEN:
        description: "Github personal access token"
        required: true

jobs:
  # ***********************************
  # Job: Build Packages
  # ***********************************
  build:
    name: "Build Packages"
    runs-on: ubuntu-latest
    outputs:
      lastVersion: ${{ steps.environment.outputs.lastVersion }}

    steps:
      - name: "Setup Environment"
        uses: panates/gh-setup-node@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 100

      - name: "Scan Environment"
        id: environment
        uses: panates/gh-repository-info@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: "Build Changelog"
        id: changelog
        uses: panates/github-actions/.github/actions/node-build-changelog@dev
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fromTag: ${{ steps.environment.outputs.prevSha }}
          toTag: ${{ steps.environment.outputs.lastSha }}

      - name: "Print changelog"
        run: |
          cat COMMIT_CHANGELOG.md

      - name: "Build Packages"
        shell: bash
        run: |
          ${{ inputs.build_script }}

      - name: "Upload Artifacts"
        uses: panates/github-actions/.github/actions/node-build-artifacts@dev
        with:
          packages: ${{ steps.environment.outputs.packages }}
