name: "Build"
on:
  workflow_call:
    inputs:
      build_script:
        type: string
        description: "Build script to be executed"
        default: 'npm run build'
    secrets:
      PERSONAL_ACCESS_TOKEN:
        description: "Github personal access token"
        required: true

jobs:
  # ***********************************
  # Job: Build Packages
  # ***********************************
  build:
    name: "Build Packages"
    runs-on: ubuntu-latest
    steps:
      - name: "Setup Environment"
        uses: panates/gh-setup-node@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Set Branch Name
        id: branch
        run: echo "BRANCH_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Use Branch Name
        run: |
          echo "This workflow is running on branch: $BRANCH_NAME"

      - name: "Scan Environment"
        id: environment
        uses: panates/gh-repository-info@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}


      - name: "Build Changelog"
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fromTag: ${{ steps.environment.outputs.prevSha }}
          toTag: ${{ steps.environment.outputs.lastSha }}
          mode: COMMIT
          outputFile: "COMMIT_CHANGELOG.md"
          configuration: 'changelog-config.json'

      - name: "debug 1"
        run: |
          echo "${{ steps.changelog.outputs.changelog }}"

      - name: "debug 2"
        run: |
          cat COMMIT_CHANGELOG.md

      #      - name: "Build"
      #        shell: bash
      #        run: |
      #          ${{ inputs.build_script }}
      #

      - name: Parse Directories
        uses: panates/github-actions/.github/actions/node-build@${{ github.ref_name }}
        with:
          packages: ${{ steps.environment.outputs.packages }}
